//void main (){}
const int POLYMORPH_TYPE_CHAIR = 310;
const int POLYMORPH_TYPE_TABLE = 311;
const int POLYMORPH_TYPE_CANDELABRA = 312;
const int POLYMORPH_TYPE_CHEST = 313;
const int POLYMORPH_TYPE_BOAT = 314;
const int POLYMORPH_TYPE_WAGON = 315;
const int POLYMORPH_TYPE_ICERIDER = 316;
const int POLYMORPH_TYPE_FLAME = 317;

