/*   Script generated by
Lilac Soul's NWN Script Generator, v. 2.2

For download info, please visit:
http://nwvault.ign.com/View.php?view=Other.Detail&id=4683&id=625    */

//Put this script OnEnter
void main()
{

object oPC = GetEnteringObject();

if (!GetIsPC(oPC)) return;

FloatingTextStringOnCreature("As you enter this clearly abandoned temple, a foul smell fills your nose. Mold and rotting leaves can be seen all over the temple and the air is filled with odd mist.", oPC);

}

