//------------------------------------------------------------------------------
// Custom Aura Script - Unholy Aura OnExit - Wastrilith Creature
//------------------------------------------------------------------------------

void main()
{
    object oTarget = GetExitingObject();
    object oCritter = GetAreaOfEffectCreator();

    //Remove all affects generated by this aura
    effect eLoop = GetFirstEffect( oTarget );
    int nAura = GetLocalInt( oTarget, "UnholyAura" );

    if( nAura == 0 )
    {
        return;
    }

    while( GetIsEffectValid( eLoop ) )
    {
        object oCreator = GetEffectCreator(eLoop);
        string sTest = GetTag(oCreator);
        if (sTest == "wastrilith" && GetEffectSubType( eLoop ) == SUBTYPE_SUPERNATURAL )
        {
            RemoveEffect(oTarget, eLoop);
        }
        eLoop = GetNextEffect(oTarget);
    }

    SetLocalInt( oTarget, "UnholyAura", 0 );
}
